### ISSUE TITLE
Make sure all the recipe images are CC0.

### ISSUE THREAD

**Issue by kazunori279** [groovenauts/iost-demo#11]

**Comment by nagachika** [comment]
In fact, some of the images are licensed under CC-BY 2.0.
I'd like to search the alternatives and replace the images.
Is it ok to proceed this replacement gradually until the demo was published at 8th May in Google I/O?

**Comment by kazunori279** [comment]
Yes, please replace them with CC0 or public domain images before I/O.

**Comment by nagachika** [comment]
It's done. Now all images of recipes and shopping items are under CC0.
