### ISSUE TITLE
Dashboard with Object Detection view only?

### ISSUE THREAD

**Issue by kazunori279** [groovenauts/iost-demo#14]
In the presentation, I'd show Object Detection at the first demo without the recipe recommendation. Can we have another page with OD only? Or you can have tabs, option button etc to hide the recipe part.

**Comment by nagachika** [comment]
I have just added new page in dashboard to show only object detection bounding box in cart camera image.
Please access http://gcp-iost.appspot.com/cartImage

**Comment by kazunori279** [comment]
confirmed!
