### ISSUE TITLE
Publish the first release of this repo by May 9

### ISSUE THREAD

**Issue by kazunori279** [groovenauts/iost-demo#17]
At the session we will refer to this repo for people who'd reproduce the demo by themselves. Can you prepare code and docs so that people can easily reproduce the demo? For example, we'd need:

- Required hardwares
- Software and hardware system architecture
- How to train the two models
- etc

**Comment by nagachika** [comment]
The due date was passed far away.
I will close the issue. Please file new one for further request.
Thanks.
