### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [groovenauts/iost-demo#19]
Hello Sir. I'm a Graphics Designer. I'm happy to see an open source project, So, I want provide a logo for you. Would you mind if I propose a new logo design for your project as my Open Source Contribution?

Thanks for your attention.

**Comment by nagachika** [comment]
Hello,
At first, sorry for late response.
Thank you for pay attention for our project and proposal of logo design.

Currently we don't think this project have to have a logo.
I will close this issue.

Anyway, I'm appreciate your activities.
