### ISSUE TITLE
[help]image not found issue in docker push command

### ISSUE THREAD

**Issue by vartult** [groovenauts/iost-demo#20]
Issue while running docker push gcr.io/${PROJECT_ID}/iost-worker
 throwing error- the push refers to repositoriy [gcr.io/250312//iost-worker]
an image does not exist locally with the tag; gcr.io/250312/iost-worker

**Comment by nagachika** [comment]
Hello vartult,
Thank you for your interest in SmartShoppingNavigator.

Did you run successfully `docker build -t gcr.io/${PROJECT_ID}/iost-worker .` in  `gke` sub-directory? Note that the trailing `.` is required.
Please confirm the docker image with name `gcr.io/250312/iost-worker` exists.

**Comment by aksaxena09** [comment]
how i will confirm that the image exist? my project id is major1-250312
can you please tell me which type of cluster i have to create on google cloud.

**Comment by nagachika** [comment]
You can just do `docker images` to show images list on your machine.
The docker image could be build on your machine, and then it should be pushed into [Google Container Registry](https://cloud.google.com/container-registry/) on your GCP Project.

**Comment by aksaxena09** [comment]
I m confused which command i have to run on pi consol and which on cloud consol.
its a humble request please elaborate and explain each step because i m new to google cloud and iot core and i m not getting any online help to learn working on google cloud.

**Comment by nagachika** [comment]
Hi, aksaxena09.
I just added a little more instructions in [README.md](https://github.com/groovenauts/SmartShoppingNavigator/blob/master/README.md#setup).
I hope this will helps.
