### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by aksaxena09** [groovenauts/iost-demo#21]
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)

extconf failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/grpc-1.11.0 for
inspection.
Results logged to
/usr/local/bundle/extensions/arm-linux/2.5.0/grpc-1.11.0/gem_make.out

An error occurred while installing grpc (1.11.0), and Bundler cannot continue.
Make sure that `gem install grpc -v '1.11.0' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  google-cloud-datastore was resolved to 1.4.0, which depends on
    google-gax was resolved to 1.2.0, which depends on
      googleapis-common-protos was resolved to 1.3.7, which depends on
        grpc
The command '/bin/sh -c bundle install --system ${bundle_install_env} && rm /usr/local/lib/ruby/gems/2.5.0/cache/*.gem && rm /usr/local/bundle/cache/*.gem' returned a non-zero code: 5

**Comment by nagachika** [comment]
Well, I think you pasted some error messages displayed with some command line operation or so...
Please show us the concrete reproducible steps. What did you do before getting this message?

**Comment by aksaxena09** [comment]
i faced this problem while running the built command

**Comment by nagachika** [comment]
I cannot reproduce the issue with docker build command like the following.

```
$ git clone https://github.com/groovenauts/SmartShoppingNavigator.git
$ cd SmartShoppingNavigator/gke
$ docker build -t xxx:latest .
```
Please show us the concrete and complete commands you did.

**Comment by aksaxena09** [comment]
docker build -t xxx:latest . 
this command is to be ran on cloud consol or raspberry pi terminal?

**Comment by aksaxena09** [comment]
please clear how to install docker packages on raspberry pi if necessary

**Comment by nagachika** [comment]
You can build docker images on the any x86 architecture system with git and docker. If you don't familiar with UNIX systems, it is recommended to use Cloud Shell to build docker images and push images to Google Cloud Container Registry. Cloud Shell provide the environment with necessary packages preinstalled.
ref. https://cloud.google.com/container-registry/docs/quickstart
