### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by aksaxena09** [groovenauts/iost-demo#22]
i ran the build command on my googlw cloud console which was successfully completed after thet i ran the push command which showing the following error

g16103160akarsh@cloudshell:~/SmartShoppingNavigator/gke (major1-250312)$ docker push gcr.io/${major1-250312}/iost-worker                                                  
The push refers to repository [gcr.io/250312/iost-worker]
cc29abc50566: Retrying in 1 second
4a8865c1c53b: Retrying in 1 second
36509bd79d2d: Retrying in 1 second
2cb427055e23: Retrying in 1 second
5435b3bbbbe5: Retrying in 2 seconds
df8351a8d25d: Waiting
da17df3ec151: Waiting
082e6ad06e82: Waiting
3bfeb766f97b: Waiting
ea1227feeccb: Waiting
9cae1895156d: Waiting
52dba9daa22c: Waiting
78c1b9419976: Waiting
unknown: Project 'project:250312' not found or deleted.

![push_error](https://user-images.githubusercontent.com/41885171/65814057-bd914a80-e1fa-11e9-959b-e47ce6e6e9f9.png)

**Comment by aksaxena09** [comment]
what next step i have to perform on raspberry pi after running these command

$ sudo systemctl enable capture
$ sudo systemctl enable dashboard

**Comment by nagachika** [comment]
You should run as below if your GCP project id is `major-250312`.

```
$ docker push gcr.io/major-250312/iost-worker
```

The `${PROJECT_ID}` is variable expansion notation of shell (bash, zsh etc...).

The instructions in README.md
```
$ export PROJCT_ID="REPLACE WITH YOUR GCP PROJECT ID HERE"
```
meant "Bind your project id to the variable with name `PROJECT_ID`". 

And then you can type as follows (you don't have to replace variable by yourself).
```
$ docker push gcr.io/${PROJECT_ID}/iost-worker
```
Your shell replace `${PROJECT_ID}` with you variable you should bind to the real value before.
