### ISSUE TITLE
deployment failed

### ISSUE THREAD

**Issue by aksaxena09** [groovenauts/iost-demo#23]
g16103160akarsh@cloudshell:~/SmartShoppingNavigator/dashboard (major1-250312)$ gcloud app deploy --version v1 app.yaml
ERROR: (gcloud.app.deploy) Staging command [/google/google-cloud-sdk/platform/google_appengine/go-app-stager /home/g16103160akarsh/SmartShoppingNavigator/dashboard/app.yaml /home/g16103160akarsh/SmartShoppingNavigator/dashboard /tmp/tmplEcvdK/tmpYoE77A] failed with return code [1].

------------------------------------ STDOUT ------------------------------------
building with dependencies from GOPATH
------------------------------------ STDERR ------------------------------------
2019/09/29 17:40:19 staging for go1.11
2019/09/29 17:40:21 Staging second-gen Standard app: failed analyzing /home/g16103160akarsh/SmartShoppingNavigator/dashboard: cannot find package "github.com/googleapis/gax-go/v2" in any of:
        ($GOROOT not set)
        /home/g16103160akarsh/gopath/src/github.com/googleapis/gax-go/v2 (from $GOPATH)
        /google/gopath/src/github.com/googleapis/gax-go/v2
GOPATH: /home/g16103160akarsh/gopath:/google/gopath
--------------------------------------------------------------------------------

**Comment by aksaxena09** [comment]
please help me out with above problem

**Comment by nagachika** [comment]
I think you did run the deploy command in Cloud Shell.
I believe the following is the complete instructions to deploy dashboard on your GCP project from Cloud Shell. 

```
go get github.com/groovenauts/SmartShoppingNavigator
cd $(echo ${GOPATH} | cut -f 1 -d:)/src/github.com/groovenauts/SmartShoppingNavigator/dashboard
go get
gcloud app deploy app.yaml -v v1
```

BTW, you have to edit `app.yaml` in `SmartShoppingNavigator/dashboard` sub-directory to use your own GCS bucket if you want to capture your own images.

**Comment by aksaxena09** [comment]
Please guide me how i can do changes in app.yaml to capture my own image

**Comment by nagachika** [comment]
Please substitute the value for `IMAGE_BUCKET` in this line with the bucket name.
https://github.com/groovenauts/SmartShoppingNavigator/blob/master/dashboard/app.yaml#L7

**Comment by aksaxena09** [comment]
From where i will get this bucket name?

**Comment by nagachika** [comment]
It's up to you. See the followings links as references.

https://cloud.google.com/storage/docs/creating-buckets
https://cloud.google.com/storage/docs/naming

**Comment by aksaxena09** [comment]
my pi camera is not showing the video in the launched app. its showing some
other random picture what should i do?

**Comment by aksaxena09** [comment]
My page is showing some already existing photos.
