### ISSUE TITLE
Showing beef menu for chicken

### ISSUE THREAD

**Issue by kazunori279** [groovenauts/iost-demo#9]
When you put chicken, the dashboard shows beef menu.

**Comment by kazunori279** [comment]
Also, shown Caprese and healthy salad for eggplant.

**Comment by nagachika** [comment]
I see. I think it's because tomato as the predicted next item and the recommended recipes are heavily depend on the predicted item.

I'd like to add some more rules to the recommended recipes based on the contents of cart.

**Comment by kazunori279** [comment]
Maybe it's better just to use the recognized item for recommending recipes for clarity of this demo. We could use the predicted next item on the "Items to add" list.

**Comment by nagachika** [comment]
I have tuned recommendation algorithm and deployed new image to GKE.
Please check the new results.

**Comment by kazunori279** [comment]
confirmed, now the recipe looks good.
